### ISSUE TITLE
Version 1.0.0 Roadmap

### ISSUE THREAD

**Issue by eclarke** [sunbeam-labs/sunbeam#100]
Putative feature list for release 1.0:

- [x]  Replace IDBA with Megahit
- [x]  Replace MGA with Prodigal
- [x]  IGV implemented as demonstration module
- [x]  Documentation on http://sunbeam.readthedocs.org
- [ ]  Compatibility with most recent Snakemake version

**Comment by eclarke** [comment]
Planning moved to Project
